import Head from 'next/head'
import Hero from '../components/Hero'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero heading='This is the heading' message='This is the message'/>
        <Hero heading='This is the heading' message='This is the message'/>
        <Hero heading='This is the heading' message='This is the message'/>

      </main>

      <footer>
      </footer>
    </div>
  )
}
